# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testSwifty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "SwiftyJSON", ">= 2.2"

  # Pods for testSwifty

  target 'testSwiftyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testSwiftyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
