# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UnitAppTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "SwiftyJSON", ">= 2.2"

  # Pods for UnitAppTest

  target 'UnitAppTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnitAppTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
